### ISSUE TITLE
Multiple tasks support

### ISSUE THREAD

**Issue by rui-cruz** [asvetliakov/vscode-run-workspace-tasks#1]
Hi, I'm using this and is very helpful, thank you 🙏
I need to run a second task, is there a way to separate with commas the tasksLabel, or use an array?

Thank you

**Comment by asvetliakov** [comment]
I haven't tried, but `dependsOn` in task definition should work. In theory 😄 

https://code.visualstudio.com/docs/editor/tasks#_compound-tasks

**Comment by rui-cruz** [comment]
Yes it works sir! thank you
